name: Build and Upload Wheels

on:
  release:
    types: [published]

jobs:
  build_wheels:
    name: Build wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Get version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        shell: bash

      - name: Update version in __init__.py
        run: |
          sed '/__version__ =/d' shardcast/__init__.py > shardcast/__init__.py.tmp
          mv shardcast/__init__.py.tmp shardcast/__init__.py
          echo "__version__ = \"$VERSION\"" >> shardcast/__init__.py
        shell: bash

      - name: Install build
        run: python -m pip install build

      - name: Build wheels
        run: python -m build --wheel

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: dist-wheels
          path: dist/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Get version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        shell: bash

      - name: Update version in __init__.py
        run: |
          sed '/__version__ =/d' shardcast/__init__.py > shardcast/__init__.py.tmp
          mv shardcast/__init__.py.tmp shardcast/__init__.py
          echo "__version__ = \"$VERSION\"" >> shardcast/__init__.py

      - name: Install build
        run: python -m pip install build

      - name: Build sdist
        run: python -m build --sdist

      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: dist-source
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          merge-multiple: true
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
